name: Repository Info

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'repository-info.json'

jobs:
  get-repository-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run script to get repository info
        run: |
          cd core
          npm run get-repository-info
        env:
          GITHUB_TOKEN: ${{ secrets.SUPER_SECRET }}

      - name: Check for changes
        run: |
          if git diff --quiet; then
            echo "No changes detected, skipping commit and push."
            exit 0
          fi

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add repository-info.json
          git commit -m "Update repository-info.json"
          git push origin HEAD:${{ github.ref }}
